# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: hello.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='hello.proto',
  package='upper',
  syntax='proto3',
  serialized_options=b'Z\"github.com/griddic/grpc_playground',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x0bhello.proto\x12\x05upper\"\x16\n\x06Player\x12\x0c\n\x04name\x18\x01 \x01(\t2-\n\x05Upper\x12$\n\x02Up\x12\r.upper.Player\x1a\r.upper.Player\"\x00\x42$Z\"github.com/griddic/grpc_playgroundb\x06proto3'
)




_PLAYER = _descriptor.Descriptor(
  name='Player',
  full_name='upper.Player',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='upper.Player.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=22,
  serialized_end=44,
)

DESCRIPTOR.message_types_by_name['Player'] = _PLAYER
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Player = _reflection.GeneratedProtocolMessageType('Player', (_message.Message,), {
  'DESCRIPTOR' : _PLAYER,
  '__module__' : 'hello_pb2'
  # @@protoc_insertion_point(class_scope:upper.Player)
  })
_sym_db.RegisterMessage(Player)


DESCRIPTOR._options = None

_UPPER = _descriptor.ServiceDescriptor(
  name='Upper',
  full_name='upper.Upper',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=46,
  serialized_end=91,
  methods=[
  _descriptor.MethodDescriptor(
    name='Up',
    full_name='upper.Upper.Up',
    index=0,
    containing_service=None,
    input_type=_PLAYER,
    output_type=_PLAYER,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_UPPER)

DESCRIPTOR.services_by_name['Upper'] = _UPPER

# @@protoc_insertion_point(module_scope)
